// <auto-generated />
using DogRallyManager.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogRallyManager.Migrations
{
    [DbContext(typeof(UserDemoContext))]
    [Migration("20240429175432_InitialMigrationSQLiteDB")]
    partial class InitialMigrationSQLiteDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DogRallyManager.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "bl4ck",
                            isAdmin = true,
                            password = "wreck"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Wreck",
                            isAdmin = false,
                            password = "Wreck"
                        },
                        new
                        {
                            Id = 3,
                            UserName = "admin",
                            isAdmin = false,
                            password = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
